# Generated by Django 5.1.1 on 2024-09-25 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='age',
            field=models.PositiveIntegerField(db_index=True, default=18, null=True, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(db_index=True, default='+996', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='salary',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
