# Generated by Django 5.1.1 on 2024-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Enter a book`s title')),
                ('author', models.CharField(max_length=250, verbose_name='Enter the book`s author')),
                ('genre', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(verbose_name='Enter the book`s price')),
                ('created_at', models.DateField(verbose_name='Enter the year of publication')),
                ('pages', models.PositiveIntegerField(verbose_name='Enter the number of pages')),
                ('cover', models.ImageField(upload_to='book/', verbose_name='Download the book`s cover')),
                ('publisher_url', models.URLField(verbose_name='Enter the publisher`s webiste address')),
                ('publisher_email', models.EmailField(max_length=254, verbose_name='Enter the publisher`s email address')),
            ],
        ),
    ]
