# Generated by Django 5.1.1 on 2024-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desciption',
            field=models.TextField(null=True, verbose_name='Add the book`s description'),
        ),
    ]
