# Generated by Django 5.1.1 on 2024-09-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'fantasy'), ('sci-fi', 'sci-fi'), ('horror', 'horror'), ('thriller', 'thriller'), ('detective', 'detective'), ('romance', 'romance'), ('classics', 'classics'), ('philosophy', 'philosophy'), ('history', 'history'), ('religion', 'religion')], max_length=200, null=True),
        ),
    ]
