# Generated by Django 5.1.1 on 2024-09-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='Enter the book`s author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(db_index=True, null=True, upload_to='book/', verbose_name='Download the book`s cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(db_index=True, null=True, verbose_name='Enter the year of publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desciption',
            field=models.TextField(db_index=True, null=True, verbose_name='Add the book`s description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'fantasy'), ('sci-fi', 'sci-fi'), ('horror', 'horror'), ('thriller', 'thriller'), ('detective', 'detective'), ('romance', 'romance'), ('classics', 'classics'), ('philosophy', 'philosophy'), ('history', 'history'), ('religion', 'religion')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='Enter the number of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='Enter the book`s price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_email',
            field=models.EmailField(db_index=True, max_length=254, null=True, verbose_name='Enter the publisher`s email address'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_url',
            field=models.URLField(db_index=True, null=True, verbose_name='Enter the publisher`s webiste address'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='Enter a book`s title'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='books.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
