# Generated by Django 5.1.1 on 2024-09-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_author_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desciption',
            new_name='description',
        ),
    ]
