# Generated by Django 5.1.1 on 2024-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_cloth_description_alter_cloth_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='tags',
            field=models.ManyToManyField(to='clothes.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
