# Generated by Django 5.1.1 on 2024-09-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_cloth_description_alter_cloth_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='description',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
