# Generated by Django 5.1.1 on 2024-09-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_cloth_description_alter_cloth_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='tags',
            field=models.ManyToManyField(db_index=True, null=True, to='clothes.tag'),
        ),
    ]
