# Generated by Django 5.1.1 on 2024-09-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_cloth_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='tags',
            field=models.ManyToManyField(db_index=True, to='clothes.tag'),
        ),
    ]
