# Generated by Django 5.1.1 on 2024-09-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='movies/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('genre', models.CharField(choices=[('thriller', 'thriller'), ('romance', 'romance'), ('detective', 'detective'), ('fantasy', 'fantasy'), ('comedy', 'comedy'), ('history', 'history'), ('action', 'action')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
